### PR TITLE
swift1.2

### PR DESCRIPTION
**Pull request by dsxNiubility**
change of swift1.2. Running in xcode6.3 beta2

### CODE REVIEW

**Comment by vikmeup** [comment]
@dsxNiubility could you explude SCLAlertViewExample.xcscheme, xcschememanagement.plist from your commit? 

Thanks.

**Comment by dsxNiubility** [comment]
@vikmeup hey, are you mean that?

**Comment by vikmeup** [comment]
@dsxNiubility there is another one hanging: UserInterfaceState.xcuserstate

Thanks. I will merge after this.

**Comment by dsxNiubility** [comment]
sorry sorry. last commit I ignore this File.  but I do it in this commit。

**Pull request merged**
