### PR TITLE
Migrates Swift-5.0

### PR DESCRIPTION
**Pull request by ChristianSteffens**
* Migrates project to Xcode-10.2
* Removes any references to actual CodeSigning identities

### CODE REVIEW

**Comment by jlaws** [comment]
Can we get this merged?

**Comment by jlaws** [comment]
@ChristianSteffens your PR doesn't update the podspec https://github.com/vikmeup/SCLAlertView-Swift/blob/master/SCLAlertView.podspec#L14

**Comment by vikmeup** [comment]
can you guys update the spec and I'm going to merge it

**Comment by ChristianSteffens** [comment]
> can you guys update the spec and I'm going to merge it

Sure thing, updated it just now.

**Comment by ChristianSteffens** [comment]
Would you mind creating a new GitHub release as well (and tag it)?

**Comment by justdan0227** [comment]
Has this been merged?  I'm still getting - Conversion to Swift 5 is available on framework?

**Comment by iceman201** [comment]
It has been merged @justdan0227

**Comment by cjcdev** [comment]
@iceman201 I'm having same issue as justdan0227, can.  Can a tag/release be created for better integration with Carthage?

**Pull request merged**
