### PR TITLE
Convert to Swift3 (Xcode 8 beta 6)

### PR DESCRIPTION
**Pull request by RemyDCF**

### CODE REVIEW

**Comment by zeusent** [comment]
+1 For this

**Comment by vikmeup** [comment]
@zeusent @RemyDCF I merged this pull request into `swift3` branch. Feel free to use it.
I will merge this changes into `master` once release version is out.

**Comment by RemyDCF** [comment]
Thanks!

**Comment by zeusent** [comment]
Awesome! Thanks!

**Comment by illyaBakurov** [comment]
Hi, I think it is time to release the swift3 branch. Will be easier to maintain cocoapods.

**Comment by vikmeup** [comment]
@illyaBakurov done! Merged into master.

created `swift2.3` branch for old version

**Pull request merged**
