### PR TITLE
Added support to be able to customize:

### PR DESCRIPTION
**Pull request by falkobuttler**
- content view color
        - content view border color
        - title color

### CODE REVIEW

**Comment by hibento** [comment]
This commit doesn't build on my System - did you try it?

**Comment by falkobuttler** [comment]
@hibento what error do you get? It successfully compiled for me.

**Comment by hibento** [comment]
Hmm, that´s weird...I got the same error on two Systems. Where UIColorFromRGB defined?    

     /Users/hibento/Repositories/External/SCLAlertView-Swift/SCLAlertView/SCLAlertView.swift:135:993: 
     Use of instance member 'UIColorFromRGB' on type 'SCLAlertView'; 
     did you mean to use a value of type 'SCLAlertView' instead?

**Comment by falkobuttler** [comment]
I moved the method `UIColorFromRGB` from the class to outside the class.... and now I just see that there must have been some weird merge conflict that reverted that part. Let me redo a PR that fixes it.

**Comment by falkobuttler** [comment]
Issues will be fixed when #185 is merged

**Pull request merged**
