### PR TITLE
[BugFix] Int Overflow

### PR DESCRIPTION
**Pull request by lastMove**
Fix issue introduced by #132

### CODE REVIEW

**Comment by nico75005** [comment]
@vikmeup @LordNali 
I think you made a mistake in your commit.
There is now randomly an overflow because of `Int(arc4random() % UInt32.max)` on line 132 in `SCLAlertView.swift`

You should change it by that one: `Int(arc4random() % UInt32(Int.max))`

**Comment by siemya** [comment]
@nico75005 @vikmeup @LordNali 
hey,
is this related with my issue #329

**Comment by LordNali** [comment]
Hmmm, changing "my" line to `Int(arc4random() % UInt32(Int.max))` would IMHO result in a crash on 64 bit systems. `Int` would be mapped to `Int64` - casting `Int64.max` to an `UInt32` should be a problem or not?

Just tried it in a Swift playground

```
Playground execution failed: error: 3264.playground:1:33: error: integer overflows when converted from 'Int' to 'UInt32'
let random = Int(arc4random() % UInt32(Int.max))
```

**Comment by siemya** [comment]
@LordNali but the current version also crashes (not always)

**Comment by LordNali** [comment]
Okay, I'll check this (again).

**Comment by nico75005** [comment]
@LordNali yes you're right. I actually did change it too `Int(arc4random() % UInt32(Int32.max))` to make sure it works fine on 32 bits and 64 bits systems. UInt32 should we more than enough.

**Comment by LordNali** [comment]
@nico75005 You're right `Int(arc4random() % UInt32.max)` crashes on 32-bit system (I just tried it in a iPhone 5 Simulator). Changing it to `Int(arc4random() % UInt32(Int32.max))` works fine.

**Pull request merged**
