### PR TITLE
Migrating Swift 2 code to Swift 3 (beta)

### PR DESCRIPTION
**Pull request by askari01**
**Migrated SCLAlertView-Swift to Swift 3**
updated  settings
commented a test, needs to be fixed

### CODE REVIEW

**Comment by vikmeup** [comment]
@askari01 could you resolve merging conflict, I will be merging this change soon. Thanks!

**Comment by askari01** [comment]
dude on vacations, I can check it by Monday. it was only a small test:

//  MARK: Needs to be Fixed        
    ``` func testButtonSelectorAndTarget() {  
         let alert = SCLAlertView()  
         let testTarget = SCLAlertView()  
         let testSelector = Selector()  
         alert.addButton("testButtonTitle", target: testTarget, selector: testSelector)  
         let button = alert.buttons[0]  
         XCTAssertTrue(button.target.isKind(of: SCLAlertView.self))  
         XCTAssertTrue(button.selector == testSelector)  
         XCTAssertTrue(button.actionType == SCLActionType.selector)  
    }```

**selector needs to be fixed just, #selector(testSelector) should work.**

**Comment by zeusent** [comment]
Are you guys planning on releasing a Swift 3 version soon?

**Comment by vikmeup** [comment]
@askari01 any change you can submit latest changes to support Swift 3.0? Thanks

**Comment by vikmeup** [comment]
https://github.com/vikmeup/SCLAlertView-Swift/pull/225

**Pull request closed without merging**
