### PR TITLE
Modification on the style of the SCLAlertView

### PR DESCRIPTION
**Pull request by rkorimba**
We can call in the different function show two optional parameter which are colorStyle and colorTextButton that customize a SCLAlertView (color style and color of the text button).

### CODE REVIEW

**Comment by vikmeup** [comment]
@rkorimba could you pull master? there is merge conflict that I can't merge.

**Comment by rkorimba** [comment]
Yes sorry, so I did the modification on the last version on SCAlertView.swift and I hope it's OK now :)

**Comment by vikmeup** [comment]
@rkorimba still merge problems. Can you check again?

**Comment by rkorimba** [comment]
@vikmeup I apply my modification on the last update of your github, I just modify the file SCLAlertView.swift in the Example. The example works fine and I test all the possibility it's ok :)

**Pull request merged**
