### PR TITLE
Hide View Issue!

### PR DESCRIPTION
**Pull request by ntanyeri**
if using selector button and after tapped the button, view don't hide.

### CODE REVIEW

**Comment by allaire** [comment]
@ntanyeri @vikmeup Should we make a setting for this? default to hide, but I have a scenario where I don't want to auto-hide?

I could make it and merge it right after if you're interested in this @vikmeup

**Comment by vikmeup** [comment]
@ntanyeri, @allaire I think it make sense to hide the button after you tapped on it.

**Comment by vikmeup** [comment]
@allaire could you push PR to have setting for this? Thanks.

**Comment by allaire** [comment]
@vikmeup I'm talking about the hidding of the alert, not the button :)

**Comment by vikmeup** [comment]
@allaire I meant alert as well.

**Pull request merged**
